plugins = []
headers = []
redirects = []

[dev]
command = "hugo server -D"
port = 1313.0
publish = "public"

[functions]

[functions."*"]

[build]
publish = "/Users/m326652/Documents/Jah'mario/website/public"
publishOrigin = "config"
commandOrigin = "config"
command = "hugo --minify"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]