[build]
  command = "hugo --minify"
  publish = "public"

[dev]
  command = "hugo server -D"
  port = 1313
  publish = "public"

# Pin Hugo version for Netlify builds
[build.environment]
  HUGO_VERSION = "0.149.0"

